Some icons
arsysop/loft-rgm pull request #84
Opened 2022-01-26 08:09 UTC by zelenyhleb

Signed-off-by: Nikifor Fedorov <nikifor.fedorov@arsysop.ru>

2022-01-26 09:16 UTC, ruspl-afed requested changes
I do not see how path in about.ini corresponds to teh real image path

2022-01-26 09:21 UTC, zelenyhleb commented
Nice finding, @ruspl-afed. Thank you!

2022-01-29 16:24 UTC, ruspl-afed requested changes
still don't see any match between image path in about.ini and real image path

2022-01-29 16:24 UTC, ruspl-afed commented on bundles/ru.arsysop.loft.rgm/about.ini
> +windowImage=images/rgm16.png
One of us is missing something important: how 
`images/rgm16.png` could lead to 
`images/icon16.png` ?

2022-01-29 16:24 UTC, ruspl-afed commented on bundles/ru.arsysop.loft.rgm/about.ini
> +featureImage=images/rgm32.png
same here

2022-02-06 10:53 UTC, ruspl-afed approved these changes
LGTM

2022-02-06 10:53 UTC, merged